//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "conference")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub platform_type: String,
    pub subject: String,
    pub description: String,
    pub start_time: String,
    pub end_time: String,
    pub conference_state: String,
    pub conference_link: String,
    pub host_id: i32,
    pub create_at: DateTime,
    pub update_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
