//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "conference")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub conference_id: String,
    pub platform_type: String,
    pub subject: String,
    pub start_time: String,
    pub end_time: String,
    pub conference_state: String,
    pub language: String,
    pub scheduser_name: String,
    pub record_type: i32,
    pub is_auto_record: i32,
    pub conf_type: String,
    pub chair_join_uri: String,
    pub guest_join_uri: String,
    pub create_at: DateTime,
    pub update_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
