//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod account;
pub mod blog_post;
pub mod credit_transaction;
pub mod monthly_score;
pub mod open_source_internship;
pub mod open_source_project;
pub mod open_source_project_maintainer;
pub mod opensource_email_template_config;
pub mod opensource_mentor;
pub mod opensource_notification_preference;
pub mod opensource_review_log;
pub mod opensource_student;
pub mod opensource_student_contract_material;
pub mod opensource_student_profile;
pub mod opensource_student_profile_draft;
pub mod order;
pub mod sea_orm_active_enums;
pub mod session;
pub mod subscription;
pub mod task;
pub mod user;
pub mod verification;
