//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod conference;
pub mod extend;
pub mod mentor;
pub mod monthly_score;
pub mod sea_orm_active_enums;
pub mod student;
pub mod task;
