//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "opensource_review_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub student_id: String,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub operator_user_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub before_status: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub after_status: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::opensource_student::Entity",
        from = "Column::StudentId",
        to = "super::opensource_student::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OpensourceStudent,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::OperatorUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::opensource_student::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpensourceStudent.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
