//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "openatom_student")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub student_status: String,
    pub contract_start_at: Option<DateTime>,
    pub contract_end_at: Option<DateTime>,
    pub submitted_at: Option<DateTime>,
    pub approved_at: Option<DateTime>,
    pub rejected_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub full_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::openatom_review_log::Entity")]
    OpenatomReviewLog,
    #[sea_orm(has_many = "super::openatom_student_profile::Entity")]
    OpenatomStudentProfile,
    #[sea_orm(has_one = "super::openatom_student_profile_draft::Entity")]
    OpenatomStudentProfileDraft,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::openatom_review_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpenatomReviewLog.def()
    }
}

impl Related<super::openatom_student_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpenatomStudentProfile.def()
    }
}

impl Related<super::openatom_student_profile_draft::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpenatomStudentProfileDraft.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
