//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "opensource_student_contract_material")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub student_id: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub submitted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::opensource_student::Entity",
        from = "Column::StudentId",
        to = "super::opensource_student::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OpensourceStudent,
}

impl Related<super::opensource_student::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpensourceStudent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
