//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "opensource_student_profile")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub student_id: String,
    #[sea_orm(column_type = "Text")]
    pub phone_number: String,
    #[sea_orm(column_type = "Text")]
    pub nationality: String,
    #[sea_orm(column_type = "Text")]
    pub id_type: String,
    #[sea_orm(column_type = "Text")]
    pub id_number: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub id_photo_urls: Json,
    #[sea_orm(column_type = "Text")]
    pub current_education_level: String,
    #[sea_orm(column_type = "Text")]
    pub school_region: String,
    #[sea_orm(column_type = "Text")]
    pub school_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub enrollment_verification_code: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub education_verification_report_url: String,
    #[sea_orm(column_type = "Text")]
    pub student_qualification_file_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub education_experience: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub internship_experience: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_experience: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub skills_statement: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub git_email: String,
    #[sea_orm(column_type = "Text")]
    pub github_id: String,
    #[sea_orm(column_type = "Text")]
    pub atomgit_email: String,
    #[sea_orm(column_type = "Text")]
    pub atomgit_account_id: String,
    #[sea_orm(column_type = "Text")]
    pub test_issue_url: String,
    pub version: i32,
    pub is_latest: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Text")]
    pub full_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::opensource_student::Entity",
        from = "Column::StudentId",
        to = "super::opensource_student::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OpensourceStudent,
}

impl Related<super::opensource_student::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpensourceStudent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
