//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "open_source_project_maintainer")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub project_id: String,
    #[sea_orm(column_type = "Text")]
    pub mentor_user_id: String,
    #[sea_orm(column_type = "Text")]
    pub login: String,
    pub max_concurrent_tasks: i32,
    pub max_task_points: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::open_source_project::Entity",
        from = "Column::ProjectId",
        to = "super::open_source_project::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OpenSourceProject,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::MentorUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    User,
}

impl Related<super::open_source_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpenSourceProject.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
