//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "open_source_internship")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub internship_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub tag_prefix: String,
    pub total_budget_cny: i32,
    pub points_per_cny: i32,
    #[sea_orm(column_type = "Text")]
    pub start_date: String,
    #[sea_orm(column_type = "Text")]
    pub end_date: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::open_source_project::Entity")]
    OpenSourceProject,
}

impl Related<super::open_source_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpenSourceProject.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
