//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::conference::Entity as Conference;
pub use super::huawei_meeting::Entity as HuaweiMeeting;
pub use super::score::Entity as Score;
pub use super::task::Entity as Task;
