//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "task_status")]
pub enum TaskStatus {
    #[sea_orm(string_value = "Open")]
    Open,
    #[sea_orm(string_value = "Invalid")]
    Invalid,
    #[sea_orm(string_value = "RequestAssign")]
    RequestAssign,
    #[sea_orm(string_value = "Assigned")]
    Assigned,
    #[sea_orm(string_value = "RequestFinish")]
    RequestFinish,
    #[sea_orm(string_value = "Finished")]
    Finished,
}
