//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    pub email_verified: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub image: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone_number: Option<String>,
    pub phone_number_verified: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stripe_customer_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub creem_customer_id: Option<String>,
    pub credit_balance: Decimal,
    pub banned: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ban_reason: Option<String>,
    pub ban_expires: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account::Entity")]
    Account,
    #[sea_orm(has_many = "super::blog_post::Entity")]
    BlogPost,
    #[sea_orm(has_many = "super::credit_transaction::Entity")]
    CreditTransaction,
    #[sea_orm(has_many = "super::openatom_review_log::Entity")]
    OpenatomReviewLog,
    #[sea_orm(has_many = "super::openatom_student::Entity")]
    OpenatomStudent,
    #[sea_orm(has_many = "super::order::Entity")]
    Order,
    #[sea_orm(has_many = "super::session::Entity")]
    Session,
    #[sea_orm(has_many = "super::subscription::Entity")]
    Subscription,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::blog_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPost.def()
    }
}

impl Related<super::credit_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditTransaction.def()
    }
}

impl Related<super::openatom_review_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpenatomReviewLog.def()
    }
}

impl Related<super::openatom_student::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpenatomStudent.def()
    }
}

impl Related<super::order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Order.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl Related<super::subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscription.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
